/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package graphique;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.Reader;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author greg
 */
public class JFrameSend extends javax.swing.JFrame {

    /**
     * Creates new form JFrameSend
     */
    public JFrameSend() {
        this.fichier = null;
        initComponents();
    }
    private File fichier;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtxtNomLocal = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxtCompteur = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtxtTextAEnvoyer = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtxtTemporisation1 = new javax.swing.JTextField();
        jCheckUrg = new javax.swing.JCheckBox();
        jCheckPush = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Send Frame");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("OU");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, -1, -1));
        getContentPane().add(jtxtNomLocal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 130, -1));

        jLabel2.setText("Nom local");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel3.setText("Compteur");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jtxtCompteur.setText("0");
        getContentPane().add(jtxtCompteur, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 130, 20));

        jLabel5.setText("Texte à envoyer");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));
        getContentPane().add(jtxtTextAEnvoyer, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 130, 20));

        jLabel6.setText("Temporisation");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jtxtTemporisation1.setText("0");
        getContentPane().add(jtxtTemporisation1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 130, 20));

        jCheckUrg.setText("Urg");
        getContentPane().add(jCheckUrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, -1, -1));

        jCheckPush.setText("Push");
        getContentPane().add(jCheckPush, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jButton1.setText("Valider");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, -1, -1));

        jButton2.setText("Choisir un fichier");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 130, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        JFileChooser chooser = new JFileChooser();
        int returnVal = chooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            this.fichier = chooser.getSelectedFile();
        }
    }//GEN-LAST:event_jButton2MouseClicked

    private String stockerDonnées() {
        if (this.fichier == null) {
            return this.jtxtTextAEnvoyer.getText();
        }
        try {
            InputStream fileReader = new FileInputStream(this.fichier);
            Reader utfReader = new InputStreamReader(fileReader);

            BufferedReader input = new BufferedReader(utfReader);
            String separator = System.getProperty("line.separator");
            final StringBuilder builder = new StringBuilder();
            String line;
            while ((line = input.readLine()) != null) {
                builder.append(line);
                builder.append(separator);
            }
            return builder.toString();

        } catch (Exception ex) {
            Logger.getLogger("JFrameSend :: " + JFrameSend.class.getName()).log(Level.SEVERE, null, ex);
        }
        return "";
    }

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        if (this.jtxtNomLocal.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nom local non précisé");
            return;
        }
        if (this.jtxtTextAEnvoyer.getText().isEmpty() && this.fichier == null) {
            JOptionPane.showMessageDialog(this, "Il faut préciser les données à envoyer");
            return;
        }
        if (!this.jtxtTextAEnvoyer.getText().isEmpty() && this.fichier != null) {
            JOptionPane.showMessageDialog(this, "Il faut préciser soit une donnée, soit un fichier");
            return;
        }
        if (this.jtxtTemporisation1.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Temporisation non précisée");
            return;
        }
        if (this.jtxtCompteur.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Compteur non précisée");
            return;
        }
        String nomLocal = this.jtxtNomLocal.getText();
        String txt = this.stockerDonnées();
        int tempo = Integer.parseInt(this.jtxtTemporisation1.getText());
        int cpt = Integer.parseInt(this.jtxtCompteur.getText());
        boolean push = this.jCheckPush.isEnabled();
        boolean urg = this.jCheckUrg.isEnabled();
        
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jButton1MouseClicked
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckPush;
    private javax.swing.JCheckBox jCheckUrg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jtxtCompteur;
    private javax.swing.JTextField jtxtNomLocal;
    private javax.swing.JTextField jtxtTemporisation1;
    private javax.swing.JTextField jtxtTextAEnvoyer;
    // End of variables declaration//GEN-END:variables
}
